import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers";
import HNavBar from "@/Components/NavBar/HNavBar";
import VNavBar from "@/Components/NavBar/VNavBar";
import KeepAlive from "@/Components/KeepAlive";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "HexVibe",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div>
					<Providers>
						<KeepAlive /> {/* Add KeepAlive component here */}
						<div className="flex h-screen w-screen">
							<div className="w-1/6 min-w-[180px] hidden sm:block">
								<VNavBar />
							</div>
							<div className="w-screen sm:w-5/6">
								<div className="w-full h-[calc(100%-64px)] sm:h-screen overflow-y-scroll">
									{children}
								</div>

								{/* Add padding to avoid phone's bottom navigation covering the bar */}
								<div
									className="w-full sm:hidden fixed bottom-0"
									style={{
										paddingBottom: "env(safe-area-inset-bottom)", // Avoid overlap with phone navigation bar
									}}>
									<HNavBar />
								</div>
							</div>
						</div>
					</Providers>
				</div>
			</body>
		</html>
	);
}
