import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers";
import HNavBar from "@/Components/NavBar/HNavBar";
import VNavBar from "@/Components/NavBar/VNavBar";
import KeepAlive from "@/Components/KeepAlive";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Instagram",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div>
					<Providers>
						<KeepAlive /> {/* Add KeepAlive component here */}
						<div className="flex h-screen w-screen">
							<div className="w-1/6 min-w-[180px] hidden sm:block">
								<VNavBar />
							</div>
							<div className="w-screen sm:w-5/6">
								<div className="flex items-center h-16 px-2 w-full sm:hidden">
									<h2 className="text-center text-4xl font-extrabold text-gray-800 mb-6">
										<span className="bg-gradient-to-r from-pink-500 via-purple-500 to-indigo-500 text-transparent bg-clip-text">
											HexVibe
										</span>
									</h2>
								</div>
								<div className="w-full h-[calc(100%-128px)] sm:h-screen overflow-y-scroll">
									{children}
								</div>

								<div className="w-full sm:hidden">
									<HNavBar />
								</div>
							</div>
						</div>
					</Providers>
				</div>
			</body>
		</html>
	);
}
